### ISSUE TITLE
Constructive Feedback Log - Adrian

### ISSUE THREAD

**Issue by ambergarcia** [G915-2-Data-Modeling-381/Midterm-Group-Project#6]
**Instructions**

Provide constructive feedback to the following members: 
- [x] Amber
- [x] Jasminder
- [ ] Oliver
- [ ] Wade

Please provide at least one; Positive & Negative feedback or a feature to implement that you like.

Store your feedback here as a comment, and close your issue when complete.

![Image](https://user-images.githubusercontent.com/21344144/199791934-dc537dfc-4814-4ad6-b642-5389c4ccaea6.png)

**Comment by adrianmnh** [comment]
# Peer Review

### `Jasminder Garcha`
Great use of the color schemes for the different types of entities. Your validation rules and defaults are thorough.

A few errors when forward engineering but here's how to fix. 
1. on the Production.Product View, uncheck the user defined SQL (1 instance)
2. the automated triggers use the table names in the sql. The problem is the table "Order" because order is also a keyword. Change the Order table to Orders, or change the triggers and wrap the word order in brackets (10 instances)

- [ ] CDM and LDM
- [x] Validation Rules
- [x] Default values forattributes
- [x] Data Domains and subdomains



![Image](https://user-images.githubusercontent.com/21344144/199791478-e0716616-b486-4f2c-94bd-2f4d2be5d756.png)



### `Amber Garcia`

Overall excellent work, great addition of theme to your Model, I was able to forward engineer it without any errors. 
- [ ] CDM and LDM
- [x] Validation Rules
- [x] Default values forattributes
- [x] Data Domains and subdomains


![Image](https://user-images.githubusercontent.com/21344144/199791882-f6c66b6e-ac76-4538-a5e3-b3e6e01a4629.png)
